apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 32000
  selector:
    app: grafana
  type: NodePort